first_setup:
	# First, install django if you don't already hve it. Requires: Python 2.7+
	# Get your sjango Version for future reference
	python -c "import django; print(django.get_version())"
	# Then ...
	python manage.py migrate
	python manage.py runserver
